import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Legacy of American Apartheid</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          The Geospatial Legacy of American Apartheid
        </h1>
          <a
            href="/map"
            className={styles.card}
          >
            <h2>Map</h2>
            <p>
              See how the painful histories of slavery, sundown towns, and other racist practices impact communities' ability to thrive today.
            </p>
          </a>
      </main>

      {/* <footer className={styles.footer}>
        Attribution
      </footer> */}
    </div>
  )
}
